service: aws-lambda-tut

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  timeout: 30
  stage: production
  region: us-east-1

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
